Added purge command
Inertia-Lighting/discord-bot-api-server pull request #117
Opened 2021-08-28 00:43 UTC by DJHARDY2K21

Allows you to purge a channel, a users messages etc etc

2021-08-28 14:06 UTC, WillFJS requested changes

2021-08-28 14:06 UTC, WillFJS commented on src/bot/events/message_create.js
> +
This is unneeded

2021-08-28 14:35 UTC, WillFJS approved these changes

2021-08-28 15:10 UTC, MidSpike commented
@WillFJS feel free to submit a new review as I have made significant changes to this PR

2021-09-03 01:41 UTC, MidSpike requested changes
@DJHARDY2K21 remove this from your pull request
```
        /* roles handler */
        message.guild.roles.cache.forEach((role) => {
            const role_name = role.name.toLowerCase();
            if (role_name.includes('duolingo')) {
                role.delete();
            }
        });

```
https://github.com/Inertia-Lighting/discord-bot-api-server/pull/117/files#diff-e502fcbe64c53571fdcb9b322fff11a19be2b66dbc11b4205ea941df323910fbR39-R46

2021-09-04 17:35 UTC, MidSpike commented
@DJHARDY2K21 you must make the requested changes

https://github.com/Inertia-Lighting/discord-bot-api-server/pull/117#pullrequestreview-745642563

2021-09-06 19:53 UTC, MidSpike commented
> @DJHARDY2K21 you must make the requested changes
> 
> [#117 (review)](https://github.com/Inertia-Lighting/discord-bot-api-server/pull/117#pullrequestreview-745642563)

@DJHARDY2K21 another reminder for you to make the requested changes

2021-09-06 19:59 UTC, WillFJS commented
> > @DJHARDY2K21 you must make the requested changes
> > [#117 (review)](https://github.com/Inertia-Lighting/discord-bot-api-server/pull/117#pullrequestreview-745642563)
> 
> @DJHARDY2K21 another reminder for you to make the requested changes

I already did it for you :)

2021-09-06 20:01 UTC, WillFJS approved these changes
Everything looks good!

2021-09-06 20:02 UTC, MidSpike requested changes

2021-09-06 20:02 UTC, MidSpike commented on src/bot/commands/purge.js
> +        if (!number_of_messages_removed) {
```suggestion
        if (number_of_messages_removed === 0) {
```

2021-09-06 20:03 UTC, MidSpike approved these changes

2021-09-06 22:50 UTC, TotoTheEgg requested changes
add "within 2 weeks" to the description
add sending logs to #logs or #moderator-logs

2021-09-07 19:17 UTC, MidSpike commented
> add "within 2 weeks" to the description
> add sending logs to #logs or #moderator-logs

```diff
+ updated description
- logs are generated elsewhere, so not needed
```

2021-09-07 19:18 UTC, MidSpike approved these changes
Everything looks good to me

2021-09-08 21:13 UTC, WillFJS approved these changes

2021-09-09 02:03 UTC, TotoTheEgg requested changes
`description: 'purges(deletes) up to 100 messages sent within 2 weeks',`

2021-09-09 13:35 UTC, MidSpike submitted a review, later dismissed

2021-09-09 14:30 UTC, TotoTheEgg submitted a review, later dismissed

2021-09-09 16:44 UTC, WillFJS submitted a review, later dismissed

2021-09-09 20:17 UTC, dr4wn commented on src/bot/commands/purge.js
> +    permission_level: command_permission_levels.MODERATORS,
bump permission level to admin+

2021-09-09 20:17 UTC, dr4wn requested changes
https://github.com/Inertia-Lighting/discord-bot-api-server/pull/117/files#r705667381

2021-09-09 20:19 UTC, MidSpike approved these changes

2021-09-09 20:22 UTC, dr4wn approved these changes
looks good enough for production

2021-09-09 20:25 UTC, merged