Update command_handler.js
Inertia-Lighting/discord-bot-api-server pull request #119
Opened 2021-09-03 01:23 UTC by dr4wn

As there are large delays for some commands such as **!identity_token**, the end user being told that they are "spamming commands" while only sending messages a few seconds *(15-20s)* could get frustrating. This PR is meant for the end user to see that the command is on cool-down, and not be told that they are spamming.

2021-09-03 01:32 UTC, MidSpike requested changes
please merge the following requested changes

2021-09-03 01:32 UTC, MidSpike commented on src/bot/handlers/command_handler.js
> +            content: `**${command}** is on cooldown!`,
```suggestion
            content: `**${command_name}** is on cooldown of ${command_cooldown_in_ms}ms!`,
```

2021-09-03 01:32 UTC, MidSpike commented on src/bot/handlers/command_handler.js
> +    const user_command_delay = current_command_epoch - last_command_epoch_for_user < command_cooldown_in_ms;
```suggestion
    const user_triggered_command_cooldown = current_command_epoch - last_command_epoch_for_user < command_cooldown_in_ms;
```

2021-09-03 01:32 UTC, MidSpike commented on src/bot/handlers/command_handler.js
> +    if (user_command_delay && user_is_not_a_staff_member) {
```suggestion
    if (user_triggered_command_cooldown && user_is_not_a_staff_member) {
```

2021-09-03 16:15 UTC, MidSpike approved these changes

2021-09-04 17:38 UTC, MidSpike commented
@rossloika @WillFJS please review this

2021-09-05 00:54 UTC, rossloika approved these changes

2021-09-05 00:54 UTC, merged