Mute command
Inertia-Lighting/discord-bot-api-server pull request #59
Opened 2021-05-28 02:36 UTC by Will3126

• Adds muted role to a user (mention or id) with reason
• Changes channel perms for all channels for muted role
• Removes muted role to a user (mention or id)

2021-05-28 02:45 UTC, Will3126 commented
Not yet tested, going to test on Friday.

2021-05-28 02:49 UTC, MidSpike requested changes

2021-05-28 02:49 UTC, MidSpike commented on src/bot/commands/mute.js
> +        Discord.Permissions.DEAFEN_MEMBERS,
this is a bug.
all permissions should start with `Discord.Permissions.FLAGS.`
most are missing this.

2021-05-28 02:49 UTC, MidSpike commented on src/bot/commands/umute.js
> +            await message.reply('Failed to remove the muted role to the user!').catch(console.warn);
Check your grammar and choice of words

2021-05-28 02:51 UTC, Will3126 commented on src/bot/commands/umute.js
> +            await message.reply('Failed to remove the muted role to the user!').catch(console.warn);
Just line 31

2021-05-28 04:23 UTC, Will3126 commented
changes made testing mostly done waiting on reviews

2021-05-29 00:34 UTC, MidSpike approved these changes
Look's good so far

2021-05-31 19:19 UTC, rossloika approved these changes

2021-05-31 21:07 UTC, MidSpike commented
Merging without @itsdrawn 's approval.
He is taking too long.

2021-05-31 21:08 UTC, merged