Discord.js V13 Upgrades
Inertia-Lighting/discord-bot-api-server pull request #71
Opened 2021-06-13 18:54 UTC by Will3126

This pull request is for discord.js v13 upgrades.

2021-06-13 18:55 UTC, MidSpike commented
Do not merge without testing

2021-06-14 01:20 UTC, Will3126 commented
help cmd v13*

2021-06-14 01:21 UTC, Will3126 commented
Do not review until done. Thanks!

2021-06-15 14:26 UTC, MidSpike requested changes
@Will3126 Please `CTRL` + `F` and find any instances of `embed:` and fully replace them with `embeds`

2021-06-15 15:41 UTC, MidSpike reviewed
@Will3126 the changes are starting to look good, just remember to keep a sharp eye when making edits

2021-06-15 17:41 UTC, Will3126 commented
> @Will3126 add trailing commas

will do!

2021-06-15 17:50 UTC, Will3126 commented
do you see any missing trailing commas

2021-06-15 17:59 UTC, MidSpike commented on src/bot/commands/quick_support.js
>  }
missing semi-colon

2021-06-15 18:00 UTC, MidSpike commented on src/bot/commands/reload.js
> +                content: `You didn't pass any command to reload, ${message.author}!`
missing comma

2021-06-15 18:01 UTC, MidSpike commented on src/bot/commands/reload.js
> +                content: `Command \`${new_command.name}\` was reloaded!`
missing comma

2021-06-15 18:02 UTC, MidSpike commented on src/bot/commands/reload.js
> +                content: `There was an error while reloading command \`${command.name}\`:\n\`\`\`${error.message}\`\`\``
missing comma

2021-06-15 18:03 UTC, MidSpike commented on src/bot/discord_client.js
> +    intens: [
intents is misspelled

2021-06-15 18:04 UTC, MidSpike submitted a review, later dismissed
please fix the things I commented on

2021-06-16 14:34 UTC, MidSpike requested changes

2021-06-16 14:34 UTC, MidSpike commented on src/bot/handlers/welcome_message_handler.js
> +};
missing newline at end of file

2021-06-16 19:49 UTC, MidSpike reviewed
after the fixes I made, things are looking good

2021-06-17 15:55 UTC, MidSpike commented
@WillFJS have you tested this branch yet?

2021-06-19 16:08 UTC, MidSpike commented
> @WillFJS have you tested this branch yet?

@WillFJS re-pinging you for this

2021-06-23 20:39 UTC, MidSpike commented
@WillFJS
![ca7ef4f2-c6ad-4449-b4e2-97591e78f236-min](https://user-images.githubusercontent.com/22574513/123164935-930d0980-d441-11eb-9297-4c2d1a0dc7d3.png)

2021-06-27 15:45 UTC, MidSpike approved these changes
After initial testing, and fixing, everything looks ready to be used.

2021-06-27 15:45 UTC, MidSpike commented
@rossloika please review this

2021-06-27 15:47 UTC, rossloika approved these changes

2021-06-28 07:16 UTC, MidSpike commented
@itsdrawn please review

2021-07-02 02:39 UTC, MidSpike commented
@rossloika @WillFJS we need to test this soon

2021-07-13 02:26 UTC, MidSpike approved these changes

2021-07-13 02:32 UTC, DJHARDY2K21 approved these changes
Great work!

2021-07-17 16:42 UTC, DJHARDY2K21 commented
Make sure you have changed the names for the events as there is a minor changes with the events. *Old ones are becoming deprecated*

2021-07-18 16:52 UTC, itsdrawn approved these changes
everything looks good

2021-07-21 02:14 UTC, MidSpike commented
@WillFJS you must test this soon

2021-07-21 02:24 UTC, WillFJS commented
looks good

2021-07-21 02:25 UTC, MidSpike commented
> and fix the merge conflicts

@WillFJS You need to fix the merge conflicts

2021-08-06 14:45 UTC, MidSpike commented
@Inertia-Lighting/discord-bot-api-server 

The time has come for finalizing our reviews on this pull request as Discord.js just released v13

2021-08-06 23:18 UTC, MidSpike approved these changes

2021-08-06 23:19 UTC, itsdrawn approved these changes
lgtm

2021-08-06 23:35 UTC, rossloika approved these changes
After some time of reading it looks good to me.

2021-08-07 00:42 UTC, merged