Moderation Commands
Inertia-Lighting/discord-bot-api-server pull request #77
Opened 2021-06-18 23:46 UTC by WillFJS

2021-06-18 23:52 UTC, WillFJS commented
The ban and kick command needs to be integrated with the database so we can have a "modlogs" command

2021-06-18 23:59 UTC, MidSpike commented
@WillFJS please finish each of the moderation commands separately on separate pull requests

2021-06-19 00:02 UTC, WillFJS commented
This pull request is ready for review!

2021-06-19 00:03 UTC, MidSpike requested changes

2021-06-19 00:03 UTC, MidSpike commented on src/bot/commands/ban.js
> +            await member.ban(reason);
member.ban accepts an object as as arg
https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=ban

2021-06-19 00:13 UTC, WillFJS commented
Moved to #78

2021-06-19 00:13 UTC, closed without merging