ModLog
Inertia-Lighting/discord-bot-api-server pull request #82
Opened 2021-06-20 16:21 UTC by WillFJS

2021-06-20 16:42 UTC, MidSpike requested changes

2021-06-20 16:42 UTC, MidSpike commented on src/bot/commands/warn.js
> +        await logModerationActionToDatabase(member.id, 'warn', Date.now(), message.member.id, reason);
`ModerationActionType` should be capitalized

2021-06-20 16:45 UTC, MidSpike requested changes
@WillFJS You need to change how you are using `logModerationActionToDatabase()` in the commands

The function accepts 2 objects

```
logModerationActionToDatabase({ discord_user_id }, { type, epoch, reason, staff_member_id });
```

2021-06-20 17:05 UTC, MidSpike requested changes
Please swap order to be:
```diff
  type
  epoch
- staff_member_id
  reason
+ staff_member_id
```

2021-06-20 21:28 UTC, MidSpike commented
@WillFJS please test this when you get a chance

2021-06-27 15:47 UTC, MidSpike commented
Everything looks good so far, I just need to finish the `moderation_actions` (`ma`) command

2021-07-12 00:33 UTC, MidSpike commented
@WillFJS please review

2021-07-13 01:59 UTC, MidSpike commented
Can confirm that everything is working as intended now

2021-07-13 02:00 UTC, MidSpike approved these changes

2021-07-13 02:02 UTC, rossloika approved these changes

2021-07-13 02:05 UTC, DJHARDY2K21 approved these changes

2021-07-13 02:13 UTC, merged