Minor updates!
Inertia-Lighting/discord-bot-api-server pull request #93
Opened 2021-07-13 03:31 UTC by DJHARDY2K21

*Added two new Quick_Support topics:

-Max HTTP Requests,

-How to download products

*Added a whitelist command,

(Un-tested due to not having access to the db).

2021-07-13 12:29 UTC, MidSpike requested changes
Please merge the suggestions that I requested

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
>      }
```suggestion
    },
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +        support_contents: 'To download your files, please visit the [website](https://inertia.lighting/products)!'
```suggestion
        support_contents: 'To download your products, go to the [products page](https://inertia.lighting/products) on our website.\nMake sure to login with the correct discord account!',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +            'download products'
```suggestion
            'downloading products',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +            'download',
```suggestion
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +        title: 'How do I download the products?',
```suggestion
        title: 'How do I download products that I have purchased?',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +        support_contents: 'To fix max HTTP Requests, Remove some lighting that you might think is unnecessary!'
```suggestion
        support_contents: 'The current limitation for sending and receiving HTTP requests is 500 requests per minute.\nTo work around this, you need to find ths script(s) that are making too many requests, then remove those script(s).',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +            'http limit'
```suggestion
            'number of requests exceeded limit',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +            'max http',
```suggestion
            'too many http requests',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
> +        title: 'Max HTTP Requests',
```suggestion
        title: 'How do I fix \"number of requests exceeded limit\"?',
```

2021-07-13 12:29 UTC, MidSpike commented on src/bot/commands/quick_support.js
>              'http requests',
```suggestion
            'enabling http requests',
```

2021-07-13 12:37 UTC, MidSpike approved these changes

2021-07-14 00:21 UTC, rossloika approved these changes

2021-07-14 02:04 UTC, WillFJS approved these changes

2021-07-14 02:05 UTC, merged